### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by Graeme22** [peter-oroszvari/tastytrade-api#1]
Hello,

I'm the maintainer of the unofficial TT API as of a few years ago. Previously we were reverse-engineering the private API but now that it's public things are a bit easier--however all of the existing functionality is still working as normal.

If you're interested in collaborating, take a look at my profile! I figured it'd be easier than reinventing the wheel.

**Comment by peter-oroszvari** [comment]
Hi, 

I'm more than happy to collaborate.
