### ISSUE TITLE
Stock / option price streaming example

### ISSUE THREAD

**Issue by leaph** [peter-oroszvari/tastytrade-api#2]
Hi Peter,
could you please add an example for printing streaming prices to the terminal for a certain stock or option?
I could not figure out completely. The dxfeed example contains some commented code for this, I can log on to tasty, receive the token and the streamer-url.

```python
from tastytrade_api.streamer.dxfeed_handler import DxFeedClient
from tastytrade_api.authentication import TastytradeAuth
import configparser

config = configparser.ConfigParser()
config.read('config.ini')

username = config.get('ACCOUNT', 'username')
password = config.get('ACCOUNT', 'password')
websocket_url = config.get('WEBSOCKET', 'websocket_url')

auth = TastytradeAuth(username, password)

auth_data = auth.login()
print("Session token:", auth.session_token)

dxfeedtoken = TastytradeAuth.get_dxfeed_token(auth)
print(dxfeedtoken)

client = DxFeedClient(websocket_url, auth.session_token)
client.connect()

client.handshake_complete.wait()

client.subscribe("Quote", "AAPL")
client.subscribe("Quote", "TSLA")

while True:
    time.sleep(1)
```

The code fails with the client.handshake_complete.wait(), with the error: "Handshake failed".
Am I missing something here?

**Comment by peter-oroszvari** [comment]
Hi, these examples were removed, I completely rewrote the dxfeed implementation in the past week, please update the module, and check the new example.

**Comment by leaph** [comment]
The new example is working fine. Thank you.

**Comment by peter-oroszvari** [comment]
I made another modification to the streamer, but I need to test it with live data. The problem was that the streamer received the data, but did not return it to the calling script, I fixed this, and also modified the Quote mapping. So if it works, there will be an example that any ticker quote can be processed and is available to the script in an easily understandable format.

**Comment by peter-oroszvari** [comment]
Example updated.

**Comment by leaph** [comment]
Working great, thanks. Where could you find the list of dxfeed future symbols, like "/VXMV23:XCBF"? On the tasty dev site and on the dxfeed site I did not find the list, quite a few links were broken there ...

**Comment by Graeme22** [comment]
> Working great, thanks. Where could you find the list of dxfeed future symbols, like "/VXMV23:XCBF"? On the tasty dev site and on the dxfeed site I did not find the list, quite a few links were broken there ...

Hi, the dxfeed site is not easy to navigate, but I compiled a few links that explain their symbology here: https://tastyworks-api.readthedocs.io/en/latest/dxfeed.html

**Comment by peter-oroszvari** [comment]
The DxFeed website is a real maze, it took me a lot of time to figure out some things. However, the answer to your specific question is simple, you can search for tickers among them here: https://symbol-lookup.dxfeed.com/ . I already reported to Tasty support two weeks ago that several links in the documentation are broken. One more tip: you can get stocks and futures through the Quote channel, but for index, you need to use the Trade channel: await client.send_subscription_message(client.websocket, "Trade", "VIX")
