### ISSUE TITLE
Does this package supports option trading?

### ISSUE THREAD

**Issue by kowkowhuang** [peter-oroszvari/tastytrade-api#3]
Hi, Just wondering we can use this package to develop out own option trading python script.

**Comment by peter-oroszvari** [comment]
It supports most of the endpoints of the API and trading endpoints are implemented... But you have to put together the whole from the parts, so if you could describe a use-case of what you would like to achieve, it would be easier for me to answer whether it is feasible or not.

**Comment by kowkowhuang** [comment]
Hi Peter,

For example, we want to fetch today's SPX (weekly) option chain, get the index of both call and put option strike price (e.g. +/- 25 strikes), each strike's bid/ask price, delta of the option.

Then 

Place a vertical spread options (e.g. sell 4190 call buy 4195 call) as an order. 

Then close this order at a lower price....etc.

**Comment by peter-oroszvari** [comment]
SPX strike prices:  you'll need the dxfeed module and the token provided by Tasty through their API (which is also implemented) to access the feed. 

Place orders: yes, you can... 

So all in all I think it's doable, yes.... 

Hint: it seems like a basic automation, which might be done easier with an optionalpha bot...

**Comment by kowkowhuang** [comment]
Hi thanks for explaining. 

Our strategy is far from a basic automation that can be done via OptionAlpha.  but we lookforward to build an TastyTrades adapter.

**Comment by peter-oroszvari** [comment]
Steps: 
- get dxfeed token
- get option chain: TastytradeInstruments class, get_option_chains method (returns only the available strikes!)
- subscribe to the Trades and Quotes channel to get continuous market data for the given strikes

Then use the TastytradeOrder class to place orders.... Hope it helps...

**Comment by kowkowhuang** [comment]
Hi Peter will you be interested to work with us (under paid contract) to develop this TastyTrade API for our trading bot?

**Comment by peter-oroszvari** [comment]
Hi, please get in touch with me in an e-mail: peter@oroszvari.hu
